---
title: "Schedule for STT 3250 - Fall 2021"
author: "Dr. Hasthika Rupasinghe"
date: 'Last Updated on: `r format(Sys.time(), "%b %d, %Y at %X")`'
output:
  bookdown::html_document2:
    highlight: textmate
    theme: yeti
    toc: true
    css: "styles.css"
---

***

**Week 1: (Aug 16 -- 20)**

* Go over syllabus
* Chapter 1: Introduction to Probability (1.1, 1.2)
* In Class Quiz 01 (Thursday, last 20 min of class)
* [Homework 1: Due Wednesday the 25th](Homework.html)


***

**Week 2: (Aug 23 -- 27)**

* Chapter 1: Introduction to Probability (1.3, 1.4, 1.5)
* In Class Quiz 02 (Thursday, last 20 min of class)
* [Homework 2](Homework.html)



***

**Week 3: (Aug 30 -- Sep 03)**

* Chapter 1: Introduction to Probability (1.4, 1.5)
* Chapter 2: Discrete Distributions (2.1)
* In Class Quiz 03 (Thursday, last 20 min of class)
* [Homework 3](Homework.html)




***

**Week 4: (Sep 06 -- 10)**

* Chapter 2: Discrete Distributions (2.2, 2.3)
* In Class Quiz 04 (Thursday, last 20 min of class)
* [Homework 4](Homework.html)



***

**Week 5: (Sep 13 -- 17)**

* Chapter 2: Discrete Distributions (2.4, 2.5, 2.6)
* In Class Quiz 05 (Thursday, last 20 min of class)
* [Homework 5](Homework.html)



***

**Week 6: (Sep 20 -- 24)**

* *Test 01: Thursday the Sep. 23rd and Covers Ch 1 and 2.*

* Chapter 3: Continuous Distributions (3.1)
* [Homework 6](Homework.html)



***

**Week 7: (Sep 27 -- Oct 01)**

* Chapter 3: Continuous Distributions (3.2)
* In Class Quiz 06 (Thursday, last 20 min of class)




***

**Week 8: (Oct 04 -- Oct 08)**

* Chapter 3: Continuous Distributions (3.3)
* Chapter 4: Bivariate Distributions (4.1)
* In Class Quiz 07 (Thursday, last 20 min of class)




***

**Week 9: (Oct 11 - 15)**

* Chapter 4: Bivariate Distributions (4.2, 4.3)
* In Class Quiz 08 (Thursday, last 20 min of class)
* [Homework 7](Homework.html)

***

**Week 10: (Oct 18 -- Oct 22)**

* Chapter 4: Bivariate Distributions (4.4)
* In Class Quiz 09 (Thursday, last 20 min of class)



***

**Week 11: (Oct 25 -- Oct 29)**

* Chapter 5: Distributions of Functions of Random Variables (5.1, 5.2, 5.3)
* In Class Quiz 10 (Thursday, last 20 min of class)
* [Homework 8](Homework.html)


***

**Week 12: (Nov 01 -- Nov 05)**


* Chapter 5: Distributions of Functions of Random Variables (5.4)


***


**Week 13: (Nov 08 -- Nov 12)**

* *Tuesday*: Watch the [Lecture Recording for 5.3](https://youtu.be/h14-ZnfXtJ4) and complete the note
* *Wednesday and Thursday*: Watch the [Lecture Recording for 5.4](https://youtu.be/kjUyH6mMwLI) and complete the note

* *Thursday*: You should get an email from me at 10.20 am with QUIZ 10 attached. Complete it (20 minutes). Please email it to me before 11am.

* Make sure to check the [Homework](Homework.html) page for upcoming due dates.

***

**Week 14: (Nov 15 -- Nov 19)**

* *Tuesday*: Work on these [Practice Problems for Exam 2](STT3250_Practice_Problems_for_Exam_2.pdf) and complete the note
* *Wednesday*: Watch the [recording where I solve the practice problems]() -(not available yet) 
* Make sure to check the [Homework](Homework.html) page for upcoming due dates.

* *Thursday*: **Test 02: Thursday the 18th of Nov. Covers Ch 3 and Ch4.**



***

**Week 15: (Nov 22 -- Nov 26 (No class on 24th and 25th))**


* Review for final

***

**Final Exam**

* TBA

***

